version: '3'
services:
  postgres:
    container_name: 'postgres'
    image: 'postgres'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  redis:
    container_name: rdb
    image: 'redis'
    ports:
      - '6379:6379'

  activemq:
    image: 'webcenter/activemq'
    container_name: 'myactivemq'
    environment:
      - "TZ=Europe/Minsk"
      - "ACTIVEMQ_ADMIN_LOGIN=admin"
      - "ACTIVEMQ_ADMIN_PASSWORD=admin"
    ports:
      - '61616:61616' # broker
      - '8161:8161'  # web