server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    user: postgres
    password: postgres

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    topic: bridgingcode-queue

springdoc:
  api-docs:
    path: /documentation_swagger

jwt:
  token_secret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  token_expired: 3600000